warn = [
  "absolute-paths-not-starting-with-crate",
  "clippy::cargo",
  "clippy::pedantic",
  "clippy::self-named-module-files",
  "clippy::undocumented-unsafe-blocks",
  "deprecated-in-future",
  "elided-lifetimes-in-paths",
  "macro-use-extern-crate",
  "missing-copy-implementations",
  "missing-debug-implementations",
  "missing-docs",
  "trivial-casts",
  "trivial-numeric-casts",
  "unreachable-pub",
  "unsafe-op-in-unsafe-fn",
  "unused-crate-dependencies",
  "unused-extern-crates",
  "unused-import-braces",
  "variant-size-differences",
]
