name: setup build environment

inputs:
  toolchain:
    default: stable
    type: string
  rustflags:
    required: false
    type: string
  target:
    required: false
    type: string
  components:
    required: false
    type: string
  update:
    default: false
    type: boolean

runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
  - uses: actions/checkout@v4
    with:
      repository: Nullus157/.github
      ref: ${{ github.workflow_sha }}
      path: .nullus.github
  - uses: actions-rust-lang/setup-rust-toolchain@v1
    with:
      toolchain: ${{ inputs.toolchain }}
      rustflags: ${{ inputs.rustflags }}
      target: ${{ inputs.target }}
      components: ${{ inputs.components }}
  - shell: bash
    if: ${{ runner.os == 'Linux' }}
    run: |
      if [ -f .github/ubuntu-packages ]; then
        readarray -t packages <.github/ubuntu-packages
        echo "Installing packages:" "${packages[@]}"
        sudo apt-get install "${packages[@]}"
      fi
  - shell: bash
    if: ${{ inputs.update }}
    run: cargo update
