#!/usr/bin/env bash

tq() {
  toml2json "supply-chain/$1" | jq -r "$2 | keys | .[]"
}

local=($(tq audits.toml '.audits'))
remote=($(tq imports.lock '.audits["first-party"].audits'))
audited=($( (echo ${local[@]}; echo ${remote[@]}) | sort -u))
imported=($(tq imports.lock '.audits | del(."first-party") | .[].audits' | sort -u))
trusted=($(tq audits.toml '.trusted'))
exempted=($(tq config.toml '.exemptions'))

log() {
  emoji=$1
  title=$2
  shift 2
  echo
  echo "<details><summary><h1>$emoji</h1><h2>$title: $#</h2></summary>"
  echo
  echo '```'
  printf '%s\n' "$@"
  echo '```'
  echo
  echo "</details>"
}

log 😍 Audited "${audited[@]}"
log 😄 Imported "${imported[@]}"
log 🙊 Trusted "${trusted[@]}"
log 🙈 Exempted "${exempted[@]}"
