
[[audits.camino]]
who = "Wim Looman <vet@nemo157.com>"
criteria = "safe-to-deploy"
delta = "1.1.4 -> 1.1.6"
notes = "No unsafe related code changed"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[audits.cesu8]]
who = "Wim Looman <vet@nemo157.com>"
criteria = "safe-to-deploy"
version = "1.1.0"
notes = """
Contains some unsafe for `str::from_utf8`. By brief inspection it looks like it
correctly handles non-utf8 input. Added some fuzzing targets and ran them for a
while with no issues detected:

https://github.com/emk/cesu8-rs/compare/master...Nemo157:cesu8-rs:fuzz
"""
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[audits.fastanvil]]
who = "Wim Looman <vet@nemo157.com>"
criteria = "safe-to-deploy"
version = "0.28.0"
notes = "One instance of unnecessary but benign unsafe usage, PR submitted to remove it."
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[audits.tracing-tree]]
who = "Wim Looman <vet@nemo157.com>"
criteria = "safe-to-deploy"
delta = "0.2.4 -> 0.2.4@git:a5af2122fd427f1b8bcab2c18b703dc2c2fa349a"
notes = "I wrote the diff"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.anstream]]
criteria = "safe-to-deploy"
user-id = 6743
start = "2023-03-16"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.anstyle]]
criteria = "safe-to-deploy"
user-id = 6743
start = "2022-05-18"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.anstyle-parse]]
criteria = "safe-to-deploy"
user-id = 6743
start = "2023-03-08"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.anstyle-query]]
criteria = "safe-to-deploy"
user-id = 6743
start = "2023-04-13"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.anstyle-wincon]]
criteria = "safe-to-deploy"
user-id = 6743
start = "2023-03-08"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.backtrace]]
criteria = "safe-to-deploy"
user-id = 2915
start = "2023-06-29"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.bitflags]]
criteria = "safe-to-deploy"
user-id = 3204
start = "2019-05-02"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.byteorder]]
criteria = "safe-to-deploy"
user-id = 189
start = "2019-06-09"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.cc]]
criteria = "safe-to-deploy"
user-id = 1
start = "2019-03-01"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.cc]]
criteria = "safe-to-deploy"
user-id = 55123
start = "2022-10-29"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.cfg-if]]
criteria = "safe-to-deploy"
user-id = 1
start = "2019-03-04"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.clap]]
criteria = "safe-to-deploy"
user-id = 6743
start = "2021-12-08"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.clap_builder]]
criteria = "safe-to-deploy"
user-id = 6743
start = "2023-03-28"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.clap_derive]]
criteria = "safe-to-deploy"
user-id = 6743
start = "2021-12-08"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.clap_lex]]
criteria = "safe-to-deploy"
user-id = 6743
start = "2022-04-15"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.color-eyre]]
criteria = "safe-to-deploy"
user-id = 43601
start = "2020-05-07"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.color-spantrace]]
criteria = "safe-to-deploy"
user-id = 43601
start = "2020-05-06"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.colorchoice]]
criteria = "safe-to-deploy"
user-id = 6743
start = "2023-04-13"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.culpa]]
criteria = "safe-to-deploy"
user-id = 782
start = "2023-06-29"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.culpa-macros]]
criteria = "safe-to-deploy"
user-id = 782
start = "2023-06-29"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.equivalent]]
criteria = "safe-to-deploy"
user-id = 539
start = "2023-02-05"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.eyre]]
criteria = "safe-to-deploy"
user-id = 43601
start = "2020-02-05"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.flate2]]
criteria = "safe-to-deploy"
user-id = 4333
start = "2020-09-30"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.getrandom]]
criteria = "safe-to-deploy"
user-id = 5059
start = "2019-06-28"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.hashbrown]]
criteria = "safe-to-deploy"
user-id = 2915
start = "2019-04-02"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.indenter]]
criteria = "safe-to-deploy"
user-id = 43601
start = "2020-02-27"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.indexmap]]
criteria = "safe-to-deploy"
user-id = 539
start = "2020-01-15"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.is-terminal]]
criteria = "safe-to-deploy"
user-id = 6825
start = "2022-01-22"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 4333
start = "2020-10-01"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 2915
start = "2021-01-27"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 1
start = "2019-03-29"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.linux-raw-sys]]
criteria = "safe-to-deploy"
user-id = 6825
start = "2021-06-12"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.memchr]]
criteria = "safe-to-deploy"
user-id = 189
start = "2019-07-07"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.once_cell]]
criteria = "safe-to-deploy"
user-id = 2699
start = "2019-05-07"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.pin-project-lite]]
criteria = "safe-to-deploy"
user-id = 33035
start = "2019-10-22"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.proc-macro2]]
criteria = "safe-to-deploy"
user-id = 3618
start = "2019-04-23"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.quote]]
criteria = "safe-to-deploy"
user-id = 3618
start = "2019-04-09"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.rand]]
criteria = "safe-to-deploy"
user-id = 1234
start = "2019-06-06"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.rustc-demangle]]
criteria = "safe-to-deploy"
user-id = 1
start = "2019-04-12"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.rustix]]
criteria = "safe-to-deploy"
user-id = 6825
start = "2021-10-29"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.serde]]
criteria = "safe-to-deploy"
user-id = 3618
start = "2019-03-01"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.serde_bytes]]
criteria = "safe-to-deploy"
user-id = 3618
start = "2019-02-25"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.serde_derive]]
criteria = "safe-to-deploy"
user-id = 3618
start = "2019-03-01"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.serde_spanned]]
criteria = "safe-to-deploy"
user-id = 6743
start = "2023-01-20"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.sharded-slab]]
criteria = "safe-to-deploy"
user-id = 1249
start = "2019-10-02"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.smallvec]]
criteria = "safe-to-deploy"
user-id = 2017
start = "2019-10-28"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618
start = "2019-03-01"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.thread_local]]
criteria = "safe-to-deploy"
user-id = 2915
start = "2019-09-07"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.toml]]
criteria = "safe-to-deploy"
user-id = 6743
start = "2022-12-14"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.toml_datetime]]
criteria = "safe-to-deploy"
user-id = 6743
start = "2022-10-21"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.toml_edit]]
criteria = "safe-to-deploy"
user-id = 6743
start = "2021-09-13"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.tracing]]
criteria = "safe-to-deploy"
user-id = 1249
start = "2019-06-28"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.tracing-attributes]]
criteria = "safe-to-deploy"
user-id = 1249
start = "2019-08-08"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.tracing-core]]
criteria = "safe-to-deploy"
user-id = 1249
start = "2019-06-20"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.tracing-error]]
criteria = "safe-to-deploy"
user-id = 1249
start = "2020-02-05"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.tracing-log]]
criteria = "safe-to-deploy"
user-id = 1249
start = "2019-06-27"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.tracing-subscriber]]
criteria = "safe-to-deploy"
user-id = 1249
start = "2019-06-27"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.tracing-tree]]
criteria = "safe-to-deploy"
user-id = 1471
start = "2023-04-20"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.unicode-ident]]
criteria = "safe-to-deploy"
user-id = 3618
start = "2021-10-02"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.uuid]]
criteria = "safe-to-deploy"
user-id = 3204
start = "2019-10-18"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.valuable]]
criteria = "safe-to-deploy"
user-id = 10
start = "2022-01-03"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.wasi]]
criteria = "safe-to-deploy"
user-id = 1
start = "2020-06-03"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.winapi]]
criteria = "safe-to-deploy"
user-id = 63
start = "2019-04-03"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-11-15"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.windows-targets]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2022-09-09"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2022-09-01"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-11-05"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-10-28"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-10-27"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-10-28"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2022-09-01"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-10-27"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"

[[trusted.winnow]]
criteria = "safe-to-deploy"
user-id = 6743
start = "2023-02-22"
end = "2024-09-12"
aggregated-from = "https://raw.githubusercontent.com/FerrisCraft/fc5-tool/main/supply-chain/audits.toml"
