jobs:
  pull_request:
    uses: ./.github/workflows/pull_request.yml
  success:
    needs: [pull_request]
    runs-on: ubuntu-latest
    steps:
    - run: true

on:
  pull_request:
    branches: [prīmum]
  push:
    branches: [staging, trying]
