jobs:
  clippy:
    name: cargo +${{ inputs.toolchain }} clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        rustflags: ${{ inputs.rustflags }}
        components: clippy
    - run:
        cargo clippy
          --workspace --all-targets --all-features --locked -- -D warnings

on:
  workflow_call:
    inputs:
      toolchain:
        default: stable
        type: string
      rustflags:
        required: false
        type: string
