jobs:
  check-features:
    name: cargo hack check --feature-powerset
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack
    - run:
        cargo hack check
          --workspace --feature-powerset --no-dev-deps
          --skip "${{ inputs.skip }}"

on:
  workflow_call:
    inputs:
      skip:
        default: ''
        type: string
