jobs:
  platforms:
    uses: ./.github/workflows/platforms.yml
  check-features:
    uses: ./.github/workflows/features.yml
    with:
      skip: ${{ inputs.skip-features }}
  updates:
    uses: ./.github/workflows/test.yml
    with:
      update: true
  minimal-versions:
    uses: ./.github/workflows/minimal-versions.yml
  deny:
    uses: ./.github/workflows/deny.yml

on:
  workflow_call:
    inputs:
      skip-features:
        default: ''
        type: string
