env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: cargo +${{ inputs.toolchain }} test ${{ inputs.args }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        rustflags: ${{ inputs.rustflags }}
    - run: cargo update
      if: ${{ inputs.update }}
    - run: cargo test --workspace --locked --all-features ${{ inputs.args }}

on:
  workflow_call:
    inputs:
      toolchain:
        default: stable
        type: string
      rustflags:
        required: false
        type: string
      args:
        required: false
        type: string
      update:
        default: false
        type: boolean
